Repository GSG-G11/herfa, pull requests merged in 2022-04, with the labels that each got.

#8 setup husky
  .husky/commit-msg
  .husky/pre-commit
  commitlint.config.js
  package-lock.json
  package.json
Labels: Awaiting Review

#9 ci: create file structure for server
  .eslintrc.json
  .vscode/settings.json
  package-lock.json
  package.json
  server/app.js
  server/controllers/index.js
  server/controllers/middleware.js
  server/controllers/services/index.js
  server/controllers/user/index.js
  server/controllers/works/index.js
  server/database/config.js
  server/database/models/index.js
  server/index.js
  server/routes/index.js
  server/test/test.test.js
  server/utils/errors.js
  server/utils/index.js
  server/utils/jwt.js
  server/utils/validation/index.js
Labels: Awaiting Review

#10 install react
  client/.eslintrc.json
  client/.gitignore
  client/package-lock.json
  client/package.json
  client/public/favicon.ico
  client/public/favicon2.ico
  client/public/index.html
  client/src/App.css
  client/src/App.tsx
  client/src/index.css
  client/src/index.tsx
  client/src/react-app-env.d.ts
  client/tsconfig.json
  package.json
Labels: Awaiting Review

#11 create server with express
  .gitignore
  client/.gitignore
  client/package-lock.json
  package-lock.json
  package.json
  server/app.js
  server/index.js
  server/routes/index.js
Labels: Done

#14 add && to fix-eslint instead of one and remove watch from test script…
  .husky/pre-commit
  package.json
Labels: Awaiting Review

#13 create connection with database by useing sequelize postegrs library
  .gitignore
  .vscode/settings.json
  env.example
  server/app.js
  server/database/config.js
  server/database/config.sql
  server/database/models/build.js
  server/database/models/index.js
  server/database/models/user.js
  server/database/models/work.js
Labels: Awaiting Review

#20 Setup Routes
  client/src/App.tsx
  client/src/Pages/Home.tsx
  client/src/Pages/LogIn.tsx
  client/src/Pages/NotFound.tsx
  client/src/Pages/Profile.tsx
  client/src/Pages/Search.tsx
  client/src/Pages/SignUp.tsx
  client/src/Pages/index.tsx
  client/src/localization/local/ar.json
  client/src/localization/local/en.json
Labels: Done, Front

#18 15 error handling
  server/app.js
  server/controllers/errors/client.js
  server/controllers/errors/custom.js
  server/controllers/errors/index.js
  server/controllers/errors/server.js
Labels: changes requested

#21 add review model to create a review table
  server/database/models/index.js
  server/database/models/review.js
Labels: Done, Back

#22 create location model
  server/database/models/build.js
  server/database/models/index.js
  server/database/models/location.js
  server/database/models/user.js
  server/routes/index.js
Labels: Awaiting Review, Back

#23 create services models
  .env.example
  env.example
  server/database/models/build.js
  server/database/models/index.js
  server/database/models/mainServices.js
  server/database/models/subServices.js
Labels: Done, Back

#26 Create node.js.yml
  .github/workflows/node.js.yml
  .gitignore
  package-lock.json
  package.json
  server/test/test.test.js
Labels: Done, documentation

#28 feat: create fake data
  package.json
  server/database/config.js
  server/database/models/location.js
  server/database/models/mainServices.js
  server/database/models/review.js
  server/database/models/work.js
  server/database/seeders/index.js
  server/database/seeders/locations.js
  server/database/seeders/review.js
  server/database/seeders/services.js
  server/database/seeders/subService.js
  server/database/seeders/users.js
  server/database/seeders/works.js
Labels: Done

#31 Get /home Route
  package.json
  server/app.js
  server/controllers/errors/index.js
  server/controllers/home/index.js
  server/controllers/index.js
  server/database/config.js
  server/database/seeders/index.js
  server/routes/index.js
  server/test/homeRoute.test.js
  server/test/test.test.js
Labels: Done, Back

#36 create top reviews component
  client/src/App.tsx
  client/src/Components/Reviews/ReviewCard.tsx
  client/src/Components/Reviews/index.tsx
  client/src/Components/Reviews/style.css
  client/src/Components/index.tsx
  client/src/Pages/Home.tsx
  client/src/localization/local/ar.json
  client/src/localization/local/en.json
Labels: Done, Front

#34 create UserInfoCard component
  client/package.json
  client/src/App.css
  client/src/App.tsx
  client/src/Components/UserInfoCard/index.tsx
  client/src/Components/UserInfoCard/style.css
  client/src/Pages/Profile.tsx
  client/src/assets/profileImg.png
  client/src/localization/local/ar.json
  client/src/localization/local/en.json
  package-lock.json
Labels: Done, Front

#33 feat: create GET /providers/:id to response user profile information
  server/controllers/user/index.js
  server/controllers/user/profile.js
  server/routes/index.js
  server/test/profile.test.js
  server/utils/validation/index.js
  server/utils/validation/requestParamsValidation.js
Labels: Done, Back

#40 create main services component home page
  client/public/images/1.png
  client/public/images/10.png
  client/public/images/2.png
  client/public/images/3.png
  client/public/images/4.png
  client/public/images/5.png
  client/public/images/6.png
  client/public/images/7.png
  client/public/images/8.png
  client/public/images/9.png
  client/src/Components/index.tsx
  client/src/Components/mainServices/MainServicesCard.tsx
  client/src/Components/mainServices/index.tsx
  client/src/Components/mainServices/style.css
  client/src/Pages/Home.tsx
  client/src/localization/local/ar.json
  client/src/localization/local/en.json
Labels: Done, Front

#43 create search by location component Home Page
  client/public/images/searchLocation.svg
  client/src/Components/Search/SearchButton.tsx
  client/src/Components/Search/index.tsx
  client/src/Components/Search/style.css
  client/src/Components/index.tsx
  client/src/Components/mainServices/style.css
  client/src/Pages/Home.tsx
  client/src/Pages/Search.tsx
  client/src/localization/local/ar.json
  client/src/localization/local/en.json
Labels: Done, Front

#39 crate work component
  client/.eslintrc.json
  client/package.json
  client/src/Components/UserInfoCard/index.tsx
  client/src/Components/WorkCard/WorkCard.tsx
  client/src/Components/WorkCard/style.css
  client/src/Components/index.tsx
  client/src/Pages/Profile.tsx
  client/src/localization/i18n.ts
  client/src/localization/local/ar.js
  client/src/localization/local/en.js
  client/src/utils/axios.js
  client/src/utils/index.ts
  client/src/utils/types/index.ts
  package-lock.json
  package.json
  server/app.js
Labels: Done

#49 welcome search component
  client/public/images/welcome-page.svg
  client/src/Components/WelcomeSearch/index.tsx
  client/src/Components/WelcomeSearch/style.css
  client/src/Components/index.tsx
  client/src/Pages/Home.tsx
  client/src/localization/local/ar.js
  client/src/localization/local/ar.json
  client/src/localization/local/en.js
  client/src/localization/local/en.json
  package-lock.json
  package.json
Labels: Done, Front

#47 Create join us component
  client/public/images/join-home-page.svg
  client/src/App.tsx
  client/src/Components/JoinUs/index.tsx
  client/src/Components/JoinUs/style.css
  client/src/Components/Reviews/index.tsx
  client/src/Components/Reviews/style.css
  client/src/Components/Search/index.tsx
  client/src/Components/index.tsx
  client/src/Components/mainServices/index.tsx
  client/src/Pages/Home.tsx
  client/src/Pages/Profile.tsx
  client/src/localization/local/ar.js
  client/src/localization/local/en.js
Labels: Done, Front

#51 add review
  server/controllers/user/addReview.js
  server/controllers/user/index.js
  server/controllers/user/profile.js
  server/routes/index.js
  server/test/reviewRout.test.js
  server/utils/validation/index.js
  server/utils/validation/reviewValidation.js
Labels: Done

#44 feat: create pagination controller
  package-lock.json
  server/controllers/index.js
  server/controllers/user/profile.js
  server/controllers/work/index.js
  server/controllers/work/workPerPage.js
  server/controllers/works/index.js
  server/routes/index.js
  server/test/work.test.js
  server/utils/validation/index.js
  server/utils/validation/workIdValidation.js
Labels: Awaiting Review, Back

#55 create user card component
  client/src/Components/UserCard/index.tsx
  client/src/Components/UserCard/style.css
  client/src/Components/index.tsx
  client/src/Pages/Search.tsx
  client/src/utils/index.ts
  client/src/utils/types/index.ts
Labels: Awaiting Review

#56 Handle home page
  client/src/App.css
  client/src/Components/Error/index.tsx
  client/src/Components/Error/style.css
  client/src/Components/JoinUs/style.css
  client/src/Components/Reviews/ReviewCard.tsx
  client/src/Components/Reviews/index.tsx
  client/src/Components/Search/SearchButton.tsx
  client/src/Components/Search/index.tsx
  client/src/Components/Search/style.css
  client/src/Components/Spinier/index.tsx
  client/src/Components/Spinier/style.css
  client/src/Components/WelcomeSearch/index.tsx
  client/src/Components/WelcomeSearch/style.css
  client/src/Components/index.tsx
  client/src/Components/mainServices/MainServicesCard.tsx
  client/src/Components/mainServices/index.tsx
  client/src/Components/mainServices/style.css
  client/src/Pages/Home.tsx
  client/src/Pages/Search.tsx
  client/src/localization/local/ar.js
  client/src/localization/local/en.js
  client/src/utils/index.ts
  client/src/utils/types/index.ts
  package.json
  server/controllers/home/index.js
Labels: Awaiting Review, Front
