Repository GSG-G11/herfa, pull requests merged in 2022-05, with the labels that each got.

#64 Context at Home Page
  client/src/App.tsx
  client/src/Components/Reviews/index.tsx
  client/src/Components/Search/SearchButton.tsx
  client/src/Components/Search/index.tsx
  client/src/Components/WelcomeSearch/index.tsx
  client/src/Components/mainServices/index.tsx
  client/src/Context/ServiceLocationContext.tsx
  client/src/Pages/Home.tsx
  client/src/utils/index.ts
  client/src/utils/types/index.ts
Labels: Awaiting Review, Front

#65 add checkauthorization middleware
  package-lock.json
  server/app.js
  server/controllers/index.js
  server/controllers/middleware.js
  server/routes/index.js
  server/utils/index.js
  server/utils/jwt.js
Labels: Awaiting Review

#62 57 search for provider
  server/controllers/index.js
  server/controllers/user/index.js
  server/controllers/user/search.js
  server/database/models/location.js
  server/database/models/mainServices.js
  server/database/models/subServices.js
  server/database/models/user.js
  server/database/seeders/users.js
  server/routes/index.js
  server/test/search.test.js
  server/utils/validation/index.js
  server/utils/validation/searchRequestValidation.js
Labels: Done

#73 create delete work route and testing it
  .github/workflows/node.js.yml
  package-lock.json
  server/controllers/index.js
  server/controllers/work/deleteWork.js
  server/controllers/work/index.js
  server/routes/index.js
  server/test/homeRoute.test.js
  server/test/work.test.js
Labels: Back, changes requested

#76 get the data of the authenticated user
  client/package.json
  client/src/App.tsx
  client/src/Context/LoggedUserContext.tsx
  client/src/utils/index.ts
  client/src/utils/types/index.ts
Labels: Awaiting Review

#69 add login controller
  server/controllers/index.js
  server/controllers/login/index.js
  server/routes/index.js
  server/test/login.test.js
  server/utils/index.js
  server/utils/jwt.js
  server/utils/validation/index.js
  server/utils/validation/loginValidation.js
Labels: Awaiting Review, Back

#74 filter search page
  client/src/Components/FilterSection/index.tsx
  client/src/Components/FilterSection/style.css
  client/src/Components/Search/SearchButton.tsx
  client/src/Components/UserCard/style.css
  client/src/Components/WelcomeSearch/index.tsx
  client/src/Components/WelcomeSearch/style.css
  client/src/Components/index.tsx
  client/src/Components/mainServices/style.css
  client/src/Pages/Search.tsx
  client/src/localization/local/ar.js
  client/src/localization/local/en.js
Labels: Front, changes requested

#81 create s3 functions to upload and delete images
  .env.example
  package-lock.json
  package.json
  server/app.js
  server/database/seeders/works.js
  server/routes/index.js
  server/test/work.test.js
  server/utils/index.js
  server/utils/s3.js
Labels: Done, Back

#83 82 search page
  client/src/Components/FilterSection/index.tsx
  client/src/Components/FilterSection/style.css
  client/src/Components/UserCard/index.tsx
  client/src/Components/UserCard/style.css
  client/src/Controllers/getSearchData.ts
  client/src/Controllers/index.ts
  client/src/Pages/Search.tsx
  client/src/localization/local/ar.js
  client/src/localization/local/en.js
  client/src/utils/index.ts
  client/src/utils/types/index.ts
  server/controllers/user/search.js
Labels: Done

#78 77 update work
  package-lock.json
  server/controllers/index.js
  server/controllers/work/editWork.js
  server/controllers/work/index.js
  server/database/seeders/works.js
  server/routes/index.js
  server/test/work.test.js
  server/utils/s3.js
  server/utils/validation/index.js
  server/utils/validation/workEditValidation.js
Labels: Awaiting Review, Back

#88 Create add work route
  server/controllers/index.js
  server/controllers/work/addWork.js
  server/controllers/work/index.js
  server/routes/index.js
  server/test/addWork.test.js
  server/utils/index.js
  server/utils/validation/index.js
  server/utils/validation/workValidation.js
Labels: Awaiting Review, Back

#90 Create navbar
  client/.eslintrc.json
  client/package.json
  client/src/App.tsx
  client/src/Components/NavBar/index.tsx
  client/src/Components/NavBar/style.css
  client/src/assets/logo_ar.png
  client/src/assets/logo_en.png
  client/src/localization/local/ar.js
  client/src/localization/local/en.js
  client/src/utils/index.ts
  client/src/utils/types/index.ts
Labels: Done, Front

#87 add login form
  client/.eslintrc.json
  client/package.json
  client/src/App.tsx
  client/src/Components/Login/LoginFrom.tsx
  client/src/Components/Login/index.tsx
  client/src/Components/Login/style.css
  client/src/Components/NavBar/index.tsx
  client/src/Components/NavBar/style.css
  client/src/Components/WorkCard/WorkCard.tsx
  client/src/Components/index.tsx
  client/src/Pages/LogIn.tsx
  client/src/Pages/Profile.tsx
  client/src/assets/login.png
  client/src/assets/logo_ar.png
  client/src/assets/logo_en.png
  client/src/localization/local/ar.js
  client/src/localization/local/en.js
  client/src/utils/index.ts
  client/src/utils/types/index.ts
  package-lock.json
Labels: Awaiting Review, Front

#98 revert on login merge
  client/.eslintrc.json
  client/package.json
  client/src/App.tsx
  client/src/Components/NavBar/index.tsx
  client/src/Components/NavBar/style.css
  client/src/Components/WorkCard/WorkCard.tsx
  client/src/Components/WorkCard/index.tsx
  client/src/Components/index.tsx
  client/src/Pages/Profile.tsx
  client/src/assets/logo_ar.png
  client/src/assets/logo_en.png
  client/src/localization/local/ar.js
  client/src/localization/local/en.js
  client/src/utils/index.ts
  client/src/utils/types/index.ts
  package-lock.json
  server/database/models/build.js
Labels: bug

#100 99 signup
  server/controllers/index.js
  server/controllers/signup/checkIsUserExists.js
  server/controllers/signup/dataToInsert.js
  server/controllers/signup/generateToken.js
  server/controllers/signup/index.js
  server/controllers/user/search.js
  server/database/models/user.js
  server/routes/index.js
  server/test/signUp.test.js
  server/utils/validation/index.js
  server/utils/validation/signUpValidation.js
Labels: Awaiting Review, Back

#104 feat: create and style footer component
  client/src/App.tsx
  client/src/Components/Footer/index.tsx
  client/src/Components/Footer/style.css
  client/src/Components/NavBar/style.css
  client/src/Components/index.tsx
  client/src/Pages/Layout.tsx
  client/src/localization/local/ar.js
  client/src/localization/local/en.js
Labels: Awaiting Review, Back

#96 create signup step1 personal information component
  client/src/Components/PersonalInformaion/index.tsx
  client/src/Components/PersonalInformaion/style.css
  client/src/Pages/SignUp.tsx
  client/src/localization/local/ar.js
  client/src/localization/local/en.js
  client/src/utils/index.ts
  client/src/utils/types/index.ts
  server/controllers/index.js
  server/controllers/signup/checkIsEmailExists.js
  server/routes/index.js
  server/test/signup.test.js
  server/test/work.test.js
  server/utils/validation/emailValidation.js
  server/utils/validation/index.js
Labels: Awaiting Review, Front

#101 Edit Component
  client/.eslintrc.json
  client/src/Components/WorkCard/index.tsx
  client/src/Components/WorkModal/index.tsx
  client/src/Components/index.tsx
  client/src/Pages/Profile.tsx
  client/src/localization/local/ar.js
  client/src/localization/local/en.js
  client/src/utils/types/index.ts
  server/controllers/errors/server.js
  server/controllers/work/addWork.js
  server/controllers/work/editWork.js
  server/test/work.test.js
  server/utils/s3.js
  server/utils/validation/workEditValidation.js
Labels: Awaiting Review

#105 create and style not found page
  client/src/Components/Error/style.css
  client/src/Pages/NotFound.tsx
Labels: Awaiting Review, Front

#95 Profile Page
  client/src/App.tsx
  client/src/Components/FilterSection/index.tsx
  client/src/Components/Footer/index.tsx
  client/src/Components/Footer/style.css
  client/src/Components/Reviews/index.tsx
  client/src/Components/UserInfoCard/index.tsx
  client/src/Components/UserInfoCard/style.css
  client/src/Components/WorkCard/index.tsx
  client/src/Components/WorkCard/style.css
  client/src/Components/WorkModal/index.tsx
  client/src/Components/WorksList/index.tsx
  client/src/Components/WorksList/style.css
  client/src/Components/index.tsx
  client/src/Controllers/getProfileData.ts
  client/src/Controllers/getWorks.ts
  client/src/Controllers/index.ts
  client/src/Pages/Home.tsx
  client/src/Pages/Profile.tsx
  client/src/utils/index.ts
  client/src/utils/types/index.ts
  package-lock.json
  server/controllers/user/profile.js
  server/database/seeders/works.js
Labels: Front, changes requested

#109 Style Pages
  client/public/index.html
  client/src/App.css
  client/src/App.tsx
  client/src/Components/FilterSection/style.css
  client/src/Components/Login/LoginFrom.tsx
  client/src/Components/Login/index.tsx
  client/src/Components/Login/style.css
  client/src/Components/NavBar/index.tsx
  client/src/Components/NavBar/style.css
  client/src/Components/PersonalInformaion/index.tsx
  client/src/Components/UserCard/index.tsx
  client/src/Components/UserCard/style.css
  client/src/Components/WorkModal/index.tsx
  client/src/Context/LoggedUserContext.tsx
  client/src/Pages/LogIn.tsx
  client/src/Pages/Search.tsx
  client/src/assets/login.jpg
  client/src/assets/login.png
  client/src/localization/local/ar.js
  client/src/localization/local/en.js
  package.json
  server/controllers/index.js
  server/controllers/login/index.js
  server/controllers/logout/index.js
  server/routes/index.js
Labels: Awaiting Review, Back, Front

#110 94 signup form2
  client/src/App.tsx
  client/src/Components/Signup/PersonalForm.tsx
  client/src/Components/Signup/ServicesForm.tsx
  client/src/Components/Signup/index.tsx
  client/src/Components/Signup/style.css
  client/src/Components/index.tsx
  client/src/Pages/SignUp.tsx
  client/src/localization/local/ar.js
  client/src/localization/local/en.js
  server/controllers/index.js
  server/controllers/signup/checkPhone.js
  server/controllers/signup/index.js
  server/routes/index.js
  server/test/signup.test.js
  server/utils/validation/phoneValidaion.js
  server/utils/validation/signUpValidation.js
Labels: Awaiting Review, Front

#107 edit and add profile image
  client/src/Components/ProfileImageUpload/index.tsx
  client/src/Components/ProfileImageUpload/style.css
  client/src/Components/UserInfoCard/index.tsx
  client/src/Controllers/getProfileData.ts
  client/src/Pages/Profile.tsx
  client/src/utils/types/index.ts
  server/app.js
  server/controllers/index.js
  server/controllers/user/index.js
  server/controllers/user/uploadImage.js
  server/routes/index.js
  server/utils/validation/imageValidation.js
  server/utils/validation/index.js
Labels: Awaiting Review

#122 redirect to user profile if auth
  client/src/App.tsx
  client/src/Pages/LogIn.tsx
  client/src/Pages/SignUp.tsx
Labels: Front, changes requested

#120 profile page, sign up
  client/src/Components/Error/style.css
  client/src/Components/ProfileImageUpload/index.tsx
  client/src/Components/ProfileImageUpload/style.css
  client/src/Components/Reviews/index.tsx
  client/src/Components/Reviews/style.css
  client/src/Components/Signup/PersonalForm.tsx
  client/src/Components/Signup/ServicesForm.tsx
  client/src/Components/Signup/style.css
  client/src/Components/UserCard/index.tsx
  client/src/Components/UserCard/style.css
  client/src/Components/UserInfoCard/index.tsx
  client/src/Components/UserInfoCard/style.css
  client/src/Components/WorkCard/index.tsx
  client/src/Components/WorkCard/style.css
  client/src/Components/WorksList/style.css
  client/src/Controllers/getProfileData.ts
  client/src/Pages/Home.tsx
  client/src/Pages/NotFound.tsx
  client/src/Pages/Profile.tsx
  client/src/Pages/SignUp.tsx
  client/src/assets/notFound.svg
  client/src/assets/profile.svg
  client/src/localization/local/ar.js
  client/src/localization/local/en.js
  client/src/utils/types/index.ts
Labels: Done, Front

#119 create edit user profile modal
  client/src/Components/EditUserData/index.tsx
  client/src/Components/Signup/ServicesForm.tsx
  client/src/Components/UserInfoCard/index.tsx
  client/src/Components/UserInfoCard/style.css
  client/src/Pages/SignUp.tsx
  client/src/localization/local/ar.js
  client/src/localization/local/en.js
Labels: Done, Front

#125 Search By name
  .env.example
  client/src/Components/Error/style.css
  client/src/Components/FilterSection/index.tsx
  client/src/Components/WelcomeSearch/index.tsx
  client/src/Components/WelcomeSearch/style.css
  client/src/Context/ServiceLocationContext.tsx
  client/src/Pages/Search.tsx
  client/src/localization/local/ar.js
  client/src/localization/local/en.js
  client/src/utils/index.ts
  client/src/utils/types/index.ts
  server/controllers/home/index.js
Labels: Done, Back, Front

#118 check translation
  client/src/App.tsx
  client/src/Components/FilterSection/index.tsx
  client/src/Components/Footer/index.tsx
  client/src/Components/NavBar/index.tsx
  client/src/Components/Search/SearchButton.tsx
  client/src/Components/Signup/ServicesForm.tsx
  client/src/Components/UserCard/index.tsx
  client/src/Components/UserInfoCard/index.tsx
  client/src/Components/WelcomeSearch/index.tsx
  client/src/Components/mainServices/MainServicesCard.tsx
  client/src/Pages/Layout.tsx
  client/src/localization/local/ar.js
  client/src/localization/local/en.js
Labels: Awaiting Review

#132 Add README
  README.md
Labels: documentation

#130 edit home page
  client/public/images/searchByName.svg
  client/public/images/searchLocation.svg
  client/src/Components/Auth/Signup/PersonalForm.tsx
  client/src/Components/Auth/Signup/style.css
  client/src/Components/Common/NavBar/index.tsx
  client/src/Components/Home/Search/SearchButton.tsx
  client/src/Components/Home/Search/index.tsx
  client/src/Components/Home/Search/style.css
  client/src/Components/Home/WelcomeSearch/index.tsx
  client/src/Components/Home/WelcomeSearch/style.css
  client/src/Components/Profile/UserInfoCard/index.tsx
  client/src/Components/Profile/WorksList/index.tsx
  client/src/Components/Search/FilterSection/index.tsx
  client/src/Pages/Search.tsx
  client/src/Pages/index.tsx
  client/src/localization/local/ar.js
  client/src/localization/local/en.js
  server/controllers/work/editWork.js
Labels: Front
